### ISSUE TITLE
Current code needs  version update and publish to npm

### ISSUE THREAD

**Issue by mzbik** [kikolobo/homebridge-lutron-homeworks#11]
**Is your feature request related to a problem? Please describe:**

From homebridge UI, you cannot install the latest code since it is not published to NPM.

**Describe the solution you'd like:**

1. Update the version number in package.json
2. Create new tag in git for the HEAD of master
3. Publish to NPM

**Describe alternatives you've considered:**

While it is possible to install directly from github, the docker deployment of homebridge does not have the correct set of tools.

**Additional context:**

None.

**Comment by kikolobo** [comment]
Thank you. 

I am putting you as a collaborator so that you can also contribute in this type of things without waiting for me. Sometimes I miss this notifications. Sorry
