### ISSUE TITLE
JSON to XML

### ISSUE THREAD

**Issue by gramster1** [kikolobo/homebridge-lutron-homeworks#14]
Requesting the XML parse tool also allow for JSON to XML in order to re upload the config into the HomeWorks OS.

**Comment by kikolobo** [comment]
So, what you are asking is that once you configure your home bridge Lutron config, you want to create an xml file with the new json file?

interesting approach but it seems will be a lot of work. Let me look into it.

**Comment by gramster1** [comment]
Yes reason being so that I can feed the changes made on the HomeKit JSON side back into Lutron XML to sync name changes etc. Would be so appreciated!

**Comment by gramster1** [comment]
Wondering if you have any update on this feature? Thanks!

**Comment by mzbik** [comment]
You need to be careful. What happens if some device is inadvertently deleted from the xml before it’s pushed back? What happens if the xml is badly formed.  

I’m pretty sure Kikolobo doesn’t want to be responsible for disappearing devices, etc...

**Comment by mzbik** [comment]
Doing a little more research, I’m not sure you >can< upload a new XML…

**Comment by kikolobo** [comment]
I haven’t had a chance to investigate this. I’m busy with real world job 😕

**Comment by kikolobo** [comment]
> Doing a little more research, I’m not sure you >can< upload a new XML…
> […](#)

You are correct. You can't. 😕 So I am closing this as it is not possible
