### ISSUE TITLE
"No Response" After Upgrading to iOS 16.1 and macOS 13.0

### ISSUE THREAD

**Issue by gramster1** [kikolobo/homebridge-lutron-homeworks#15]
**Describe Your Problem:**
After upgrading to iOS 16.1, all accessories from homeworks show no response. The issue persists after restart of host Synology has and occurs across multiple devices running macOS Monterey and macOS Ventura and iOS 16.0.3 and iOS 16.1

**Logs:**

Logs appear normal and show live status of homeworks lights when toggled with physical switch on wall

**Environment:**

* **Plugin Version**: homebridge-homeworks v0.7.0
* **Homebridge Version** 1.5.0
* **Node.js Version**: 16.18.0
* **Operating System**: Docker on Synology NAS DS2415+ DSM 7.1.1-42962 Update 1

**Comment by kikolobo** [comment]
Thank you for your report. I will update to iOS 16.1 and check this out. It seems to me more of an issue with HomeBridge and the Home App, but I won’t blame it on that until I investigate further. 

Keep you posted and please let me know if you find something else.

**Comment by kikolobo** [comment]
Sorry I closed it accidentally

**Comment by kikolobo** [comment]
I just updated to iOS 16.1 on iPhone and iPad. 

I can’t replicate the issue you are reporting. Can you update this if your  issue persist?
