### ISSUE TITLE
Feature request: Lutron Thermostats (within HomeWorks/RadioRa2)

### ISSUE THREAD

**Issue by jfinestone** [kikolobo/homebridge-lutron-homeworks#2]
Would be great to add Lutron Thermostats to this HomeBridge integration.  Currently, they are unsupported in Lutron's native HomeKit integration so you have to launch the Lutron superslow app everytime you want to change the mode, temp, fan etc....

Lutron calls its thermostat an HVAC CONTROLLER.

See https://www.lutron.com/TechnicalDocumentLibrary/040249.pdf
Pages labeled 10-11 for the full telnet integration.

Happy (and eager!) to test.

Thanks.

**Comment by kikolobo** [comment]
Let me take a look. It’s difficult because I don’t own one. But will sure take a look. Tomorrow I will put some time in doing some house keeping issues. Let me see what will it take.
