### ISSUE TITLE
"updateHomeKitName": "on", has no effect

### ISSUE THREAD

**Issue by gramster1** [kikolobo/homebridge-lutron-homeworks#20]
**Describe The Bug:**
When integration names are changed in the Json config they are not automatically updated in HomeKit.

**To Reproduce:**
Modify any integration name and restart HomeKit, old name remains the same on HomeKit side. This is verified by turning on the light from accessories on the HomeBridge web ui, it activates the light with the old name in HomeKit.

**Expected behavior:**
Names in the JSON config should update in HomeKit automatically.

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
   "host": "10.0.0.40",
    "apiPort": "23",
    "username": "REDACTED",
    "password": "REDACTED",
    "updateHomeKitName": "on",
    "devices": [
        {
            "name": "Exterior Lower Den",
            "integrationID": "105",
            "isDimmable": true
        },
        {
            "name": "Lower Den Main",
            "integrationID": "104",
            "isDimmable": true
        },
        {
            "name": "Lower Den Powder Hall",
            "integrationID": "144",
            "isDimmable": true
        },
        {
            "name": "Piano Area Powder Main",
            "integrationID": "153",
            "isDimmable": true
        },
        {
            "name": "Exterior Parking",
            "integrationID": "167",
            "isDimmable": true
        },
        {
            "name": "Exterior Entry Overhead",
            "integrationID": "94",
            "isDimmable": true
        },
        {
            "name": "Patio East",
            "integrationID": "114",
            "isDimmable": true
        },
        {
            "name": "Patio West",
            "integrationID": "113",
            "isDimmable": true
        },
        {
            "name": "Interior Lower Stair In-Wall",
            "integrationID": "166",
            "isDimmable": true
        },
        {
            "name": "Interior Skylights",
            "integrationID": "98",
            "isDimmable": true
        },
        {
            "name": "Upper Hall",
            "integrationID": "138",
            "isDimmable": true
        },
        {
            "name": "Interior Entry Lights",
            "integrationID": "95",
            "isDimmable": true
        },
        {
            "name": "Upper stair in-wall",
            "integrationID": "80",
            "isDimmable": true
        },
        {
            "name": "Entry Hall",
            "integrationID": "62",
            "isDimmable": true
        },
        {
            "name": "Garage Lower Hall",
            "integrationID": "157",
            "isDimmable": true
        },
        {
            "name": "Garage Perimeter",
            "integrationID": "163",
            "isDimmable": true
        },
        {
            "name": "Garage Ramp",
            "integrationID": "162",
            "isDimmable": true
        },
        {
            "name": "Garage Entry",
            "integrationID": "161",
            "isDimmable": true
        },
        {
            "name": "Garage Middle",
            "integrationID": "160",
            "isDimmable": true
        },
        {
            "name": "Kids Family Room Bar",
            "integrationID": "92",
            "isDimmable": true
        },
        {
            "name": "Kids Family Room North",
            "integrationID": "75",
            "isDimmable": true
        },
        {
            "name": "Kids Family Room South",
            "integrationID": "99",
            "isDimmable": true
        },
        {
            "name": "Kids Family Room Center",
            "integrationID": "68",
            "isDimmable": true
        },
        {
            "name": "Kids Family Room Laundry",
            "integrationID": "93",
            "isDimmable": true
        },
        {
            "name": "Upper Office Over Desks",
            "integrationID": "139",
            "isDimmable": true
        },
        {
            "name": "Upper Office Deck",
            "integrationID": "137",
            "isDimmable": true
        },
        {
            "name": "Upper Office Main",
            "integrationID": "133",
            "isDimmable": true
        },
        {
            "name": "Master Bedroom Deck",
            "integrationID": "145",
            "isDimmable": true
        },
        {
            "name": "Master Bedroom Entry",
            "integrationID": "135",
            "isDimmable": true
        },
        {
            "name": "Master Bedroom Main",
            "integrationID": "127",
            "isDimmable": true
        },
        {
            "name": "Master Bedroom Skylight",
            "integrationID": "120",
            "isDimmable": true
        },
        {
            "name": "His Shower",
            "integrationID": "131",
            "isDimmable": true
        },
        {
            "name": "His Bath Toilet",
            "integrationID": "126",
            "isDimmable": true
        },
        {
            "name": "His Bath Main",
            "integrationID": "125",
            "isDimmable": true
        },
        {
            "name": "His Bath Sconces",
            "integrationID": "124",
            "isDimmable": true
        },
        {
            "name": "Her Bath Main",
            "integrationID": "129",
            "isDimmable": true
        },
        {
            "name": "Her Closet",
            "integrationID": "134",
            "isDimmable": true
        },
        {
            "name": "Her Bath Chandelier",
            "integrationID": "118",
            "isDimmable": true
        },
        {
            "name": "Her Bath Sconces",
            "integrationID": "130",
            "isDimmable": true
        },
        {
            "name": "Sons Room Shower",
            "integrationID": "101",
            "isDimmable": true
        },
        {
            "name": "Sons Room Bath",
            "integrationID": "96",
            "isDimmable": true
        },
        {
            "name": "Sons Room Above Bed",
            "integrationID": "121",
            "isDimmable": true
        },
        {
            "name": "Sons Room Main",
            "integrationID": "102",
            "isDimmable": true
        },
        {
            "name": "Sons Room Deck",
            "integrationID": "81",
            "isDimmable": true
        },
        {
            "name": "Sons Room Entry",
            "integrationID": "100",
            "isDimmable": true
        },
        {
            "name": "Sons Room Bath Sconce",
            "integrationID": "97",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Bath Main",
            "integrationID": "186",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Toilet",
            "integrationID": "77",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Shower",
            "integrationID": "72",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Main",
            "integrationID": "123",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Deck",
            "integrationID": "76",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Entry",
            "integrationID": "74",
            "isDimmable": true
        },
        {
            "name": "Daughters Room Closet",
            "integrationID": "73",
            "isDimmable": true
        },
        {
            "name": "Kitchen Under Counter",
            "integrationID": "108",
            "isDimmable": true
        },
        {
            "name": "Kitchen Main",
            "integrationID": "60",
            "isDimmable": true
        },
        {
            "name": "Kitchen Pendants",
            "integrationID": "63",
            "isDimmable": true
        },
        {
            "name": "Family Room Main",
            "integrationID": "61",
            "isDimmable": true
        },
        {
            "name": "Family Room Game Area",
            "integrationID": "67",
            "isDimmable": true
        },
        {
            "name": "Pool Powder Entry",
            "integrationID": "65",
            "isDimmable": true
        },
        {
            "name": "Pool Powder Bath",
            "integrationID": "189",
            "isDimmable": true
        },
        {
            "name": "Pool Powder Sconce",
            "integrationID": "71",
            "isDimmable": true
        },
        {
            "name": "Pool Powder Main",
            "integrationID": "64",
            "isDimmable": true
        },
        {
            "name": "Dining Room Main",
            "integrationID": "155",
            "isDimmable": true
        },
        {
            "name": "Dining Room Chandelier",
            "integrationID": "148",
            "isDimmable": true
        },
        {
            "name": "Sitting Area",
            "integrationID": "115",
            "isDimmable": true
        },
        {
            "name": "Piano Area Sconces",
            "integrationID": "154",
            "isDimmable": true
        },
        {
            "name": "Piano Area Powder Sconce",
            "integrationID": "151",
            "isDimmable": true
        },
        {
            "name": "Piano Area Main",
            "integrationID": "149",
            "isDimmable": true
        },
        {
            "name": "Piano Area Bar",
            "integrationID": "111",
            "isDimmable": true
        },
        {
            "name": "UNK Christmas 2",
            "integrationID": "169",
            "isDimmable": true
        },
        {
            "name": "UNK Pool Lights Garage Side",
            "integrationID": "168",
            "isDimmable": true
        },
        {
            "name": "UNK X3 Dupe",
            "integrationID": "147",
            "isDimmable": true
        },
        {
            "name": "UNK X2 Dupe",
            "integrationID": "146",
            "isDimmable": true
        },
        {
            "name": "UNK X3 Dup",
            "integrationID": "143",
            "isDimmable": true
        },
        {
            "name": "UNK X2 Dup",
            "integrationID": "142",
            "isDimmable": true
        },
        {
            "name": "UNK Ext East Christmas",
            "integrationID": "141",
            "isDimmable": true
        },
        {
            "name": "UNK Ext Zone 6",
            "integrationID": "140",
            "isDimmable": true
        },
        {
            "name": "UNK Ext Zone 3",
            "integrationID": "136",
            "isDimmable": true
        },
        {
            "name": "UNK 5-Also X1",
            "integrationID": "122",
            "isDimmable": true
        },
        {
            "name": "UNK Pool Perimeter",
            "integrationID": "119",
            "isDimmable": true
        },
        {
            "name": "UNK Ext Backyard Perimeter",
            "integrationID": "112",
            "isDimmable": true
        },
        {
            "name": "UNK Ext LV Lights TBD",
            "integrationID": "107",
            "isDimmable": true
        },
        {
            "name": "UNK",
            "integrationID": "106",
            "isDimmable": true
        },
        {
            "name": "UNK Pump",
            "integrationID": "117",
            "isDimmable": true
        },
        {
            "name": "UNK Fire Whip",
            "integrationID": "116",
            "isDimmable": true
        },
        {
            "name": "UNK KIDS FAM",
            "integrationID": "9",
            "isDimmable": true
        },
        {
            "name": "Upper Office Under Counter",
            "integrationID": "132",
            "isDimmable": true
        },
        {
            "name": "bl",
            "integrationID": "187",
            "isDimmable": true
        },
        {
            "name": "bj",
            "integrationID": "185",
            "isDimmable": true
        },
        {
            "name": "bi",
            "integrationID": "184",
            "isDimmable": true
        },
        {
            "name": "bh",
            "integrationID": "183",
            "isDimmable": true
        },
        {
            "name": "bg",
            "integrationID": "182",
            "isDimmable": true
        },
        {
            "name": "bf",
            "integrationID": "181",
            "isDimmable": true
        },
        {
            "name": "be",
            "integrationID": "180",
            "isDimmable": true
        },
        {
            "name": "bd",
            "integrationID": "179",
            "isDimmable": true
        },
        {
            "name": "bc",
            "integrationID": "178",
            "isDimmable": true
        },
        {
            "name": "bb",
            "integrationID": "177",
            "isDimmable": true
        },
        {
            "name": "ba",
            "integrationID": "176",
            "isDimmable": true
        },
        {
            "name": "az",
            "integrationID": "175",
            "isDimmable": true
        },
        {
            "name": "ay",
            "integrationID": "174",
            "isDimmable": true
        },
        {
            "name": "ax",
            "integrationID": "173",
            "isDimmable": true
        },
        {
            "name": "aw",
            "integrationID": "172",
            "isDimmable": true
        },
        {
            "name": "av",
            "integrationID": "171",
            "isDimmable": true
        },
        {
            "name": "au",
            "integrationID": "170",
            "isDimmable": true
        },
        {
            "name": "ac",
            "integrationID": "152",
            "isDimmable": true
        },
        {
            "name": "UNK Piano Area Chandelier",
            "integrationID": "150",
            "isDimmable": true
        },
        {
            "name": "e",
            "integrationID": "128",
            "isDimmable": true
        },
        {
            "name": "UNK Piano Area Bar",
            "integrationID": "110",
            "isDimmable": true
        },
        {
            "name": "UNK Piano Area Bar Seats",
            "integrationID": "109",
            "isDimmable": true
        },
        {
            "name": "Exterior Perimeter",
            "integrationID": "103",
            "isDimmable": true
        },
        {
            "name": "cc",
            "integrationID": "90",
            "isDimmable": true
        },
        {
            "name": "UNK-br",
            "integrationID": "78",
            "isDimmable": true
        },
        {
            "name": "UNK-Pool Powder WC",
            "integrationID": "69",
            "isDimmable": true
        },
        {
            "name": "UNK 2",
            "integrationID": "66",
            "isDimmable": true
        },
        {
            "name": "Storage Main",
            "integrationID": "156",
            "isDimmable": true
        },
        {
            "name": "Theater Powder",
            "integrationID": "158",
            "isDimmable": true
        },
        {
            "name": "Theater Main",
            "integrationID": "159",
            "isDimmable": true
        },
        {
            "name": "Exterior Entry Sconces",
            "integrationID": "165",
            "isDimmable": true
        },
        {
            "name": "UNK 4",
            "integrationID": "164",
            "isDimmable": true
        },
        {
            "name": "af",
            "integrationID": "91",
            "isDimmable": true
        },
        {
            "name": "ad",
            "integrationID": "89",
            "isDimmable": true
        },
        {
            "name": "ac",
            "integrationID": "88",
            "isDimmable": true
        },
        {
            "name": "ab",
            "integrationID": "87",
            "isDimmable": true
        },
        {
            "name": "aa",
            "integrationID": "86",
            "isDimmable": true
        },
        {
            "name": "z",
            "integrationID": "85",
            "isDimmable": true
        },
        {
            "name": "y",
            "integrationID": "84",
            "isDimmable": true
        },
        {
            "name": "w",
            "integrationID": "82",
            "isDimmable": true
        },
        {
            "name": "t",
            "integrationID": "79",
            "isDimmable": true
        }
    ],
    "_bridge": {
        "username": "REDACTED",
        "port": REDACTED
    },
    "platform": "Homeworks"
}

**Environment:**

* **Plugin Version**: 0.7.0
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.12.1
* **Operating System**: Docker on Synology DSM 7.1.1-42962 Update 3

**Comment by kikolobo** [comment]
Sorry for the long wait. I will take a look at this. I am very busy at the moment but will attempt to fix next weekend.

**Comment by kikolobo** [comment]
I tried this, and if you restart the Homebridge, it will update the names of your HomeKit. Provided the bridges (apple tv's and such) are powered on when doing this.
