### ISSUE TITLE
Relay control

### ISSUE THREAD

**Issue by sandywoodward** [kikolobo/homebridge-lutron-homeworks#3]
Hi - all looks good. New to homebridge but have Lutron running lights nicely in HomeKit through their official bridge. 
I use Lutron to control somfy blinds through relays all working perfectly but Lutron doesn’t pass there through to HomeKit for control. Any ideas?

**Comment by kikolobo** [comment]
Well, this plug-in will turn off relays. Basically any output. 

In a new release I will also try to support button/key presses. That should help talk to other accessories.

let me know how it goes.

I built this plugin because the bridge limits the number of fixtures to talk to.
