### ISSUE TITLE
Defect in parsing xml with scenes

### ISSUE THREAD

**Issue by mzbik** [kikolobo/homebridge-lutron-homeworks#8]
My system contains scenes.  When parsing the xml file, the line (attached) is interpreted as a device with integration id '4805' with device name '0' 

This is using the latest (as of today) version of the converter directly from github

As a first approximation, the parsing works only OK.  You might want to consider using a correct parser like xml-js and then walking the json to emit the device descriptions.

[bad_xml.txt](https://github.com/kikolobo/homebridge-lutron-homeworks/files/7797299/bad_xml.txt)

**Comment by kikolobo** [comment]
Woa!
Let me take a look. If you have good JS knowledge you can consider a pull request!


But let me take a look!

**Comment by mzbik** [comment]
Working on it. Key is convert it to json and do a recursive walk.

My reading of it is that you are looking for Output in an Area and then use the Name and IntegrationID to build your entries.

Questions for you:

1. This will include shades as well as lights.  How do you plan on handling shades?

2. You assume that everything is dimmable. The OutputType field is a string that you might be able to infer if its dimmable or a toggle.

I'll build something that will generate a slightly richer json with the OutputTypes included (shades and switch types) and send a pull request.

**Comment by kikolobo** [comment]
That is great!

For now the only thing that the app does is clean the file and parse it.

Doesn’t do much more.

Saludos!
FLG

**Comment by mzbik** [comment]
What are your plans for this plugin?  At present there are no good homebridge plugins for lutron. What documentation are you working from?

**Comment by kikolobo** [comment]
I really don’t have plans. I was hoping to add support for keypads so that it can serve as inputs for home bridge and control drapes too.

**Comment by mzbik** [comment]
So I’m working on a cleaned up version that correctly creates shades as well as lights.  A pr will be there in a week or so.
